version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - /usr/share/influxdb/data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=_internal
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.1
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=['http://elasticsearch:9200']
      - setup.kibana.host="http://kibana:5601"
      - setup.template.enabled=true
      - logging.to_files=false
    depends_on:
      - elasticsearch
      - kibana
  grafana:
    image: grafana/grafana:latest
    user: "0"
    ports:
      - '3000:3000'
    volumes:
      - /usr/share/grafana/data:/var/lib/grafana
    links:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:  
  influxdb-storage:
  grafana-storage: